# Generated by Django 3.1.6 on 2021-02-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_no', models.IntegerField(max_length=14)),
                ('ifsc_code', models.IntegerField(max_length=6)),
            ],
        ),
    ]
