# Generated by Django 3.1.5 on 2021-03-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_info',
            name='upi',
            field=models.IntegerField(default=0),
        ),
    ]
