# Generated by Django 3.1.5 on 2021-03-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20210304_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_info',
            name='upi_staus',
            field=models.IntegerField(default=0),
        ),
    ]
