# Generated by Django 3.1.5 on 2021-03-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_users_info_upi_staus'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_info',
            name='acno',
            field=models.CharField(default=0, max_length=14),
        ),
        migrations.AddField(
            model_name='users_info',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
