# Generated by Django 3.1.5 on 2021-03-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_auto_20210308_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_info',
            name='status',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='upi',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='upi_staus',
            field=models.IntegerField(default=None),
        ),
    ]
