# Generated by Django 3.1.5 on 2021-03-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_auto_20210310_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_info',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='upi',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='upi_staus',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
