# Generated by Django 3.1.5 on 2021-03-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addbankaccount', '0005_bank_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='acno',
            field=models.IntegerField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
