# Generated by Django 3.1.7 on 2021-02-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
