# Generated by Django 3.1.7 on 2021-02-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0002_delete_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_info',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.IntegerField(max_length=10)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password1', models.CharField(max_length=500)),
            ],
        ),
    ]
