# Generated by Django 3.1.5 on 2021-03-08 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20210306_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_info',
            name='acno',
        ),
        migrations.RemoveField(
            model_name='users_info',
            name='balance',
        ),
    ]
