# Generated by Django 3.1.7 on 2021-02-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20210226_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_info',
            old_name='mobile',
            new_name='mobileno',
        ),
    ]
