# Generated by Django 3.1.5 on 2021-03-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_auto_20210226_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_info',
            old_name='mobileno',
            new_name='mobile',
        ),
    ]
