# Generated by Django 3.1.5 on 2021-03-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_auto_20210310_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_info',
            name='status',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='upi',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='upi_staus',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
