# Generated by Django 3.1.5 on 2021-03-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_auto_20210303_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_info',
            old_name='password1',
            new_name='password',
        ),
    ]
