# Generated by Django 3.1.5 on 2021-03-05 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_users_info_upi_staus'),
        ('addbankaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.users_info'),
        ),
    ]
