# Generated by Django 3.1.5 on 2021-03-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addbankaccount', '0002_bank_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='status',
            field=models.IntegerField(default=None),
        ),
    ]
