# Generated by Django 3.1.5 on 2021-03-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addbankaccount', '0006_auto_20210328_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='acno',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
