# Generated by Django 3.1.5 on 2021-03-07 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('Transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_mobile', models.CharField(max_length=10)),
                ('sender_acno', models.CharField(max_length=14)),
                ('sender_amount', models.IntegerField()),
                ('sender_purpose', models.CharField(max_length=100000)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_mobile', models.CharField(max_length=10)),
                ('receiver_acno', models.CharField(max_length=14)),
            ],
        ),
    ]
