# Generated by Django 3.1.7 on 2021-03-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(default='mobileno', max_length=10),
        ),
    ]
