# Generated by Django 3.1.5 on 2021-03-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_payment', '0002_transaction_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender_username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
